### PR TITLE
add swden_ww3_read_ascii.m  examples/Example_Directional_Spectral_Den…

### PR DESCRIPTION
**Pull request by aliabdolali**
This PR add a new function to read spec files in ascii format with a corresponding example to check its functionality. 
- ww3tools/matlab_tools/swden_ww3_read_ascii.m
- examples/Example_Directional_Spectral_Density_NDBC_ascii.m
In addition, a couple of files and examples are modified to accomodate some small features like log scale on polar plots, modularities, ... 

Please also include the following information: 
* Add any suggestions for a reviewer  @MatthewMasarik-NOAA @ricampos 
* Mention any labels that should be added:  _enhancement_

### Commit Message
add swden_ww3_read_ascii.m (read spec file in WW3 ascii format)
### Check list  

- [ x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
 
### Testing

* How were these changes tested?
The  examples/Example_Directional_Spectral_Density_NDBC_ascii.m checks the functionality of the new feature.

### CODE REVIEW

**Comment by aliabdolali** [comment]
@MatthewMasarik-NOAA @ricampos could you review and merge if approved at your earliest convenience?

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA @ricampos could you review and merge if approved at your earliest convenience?

@aliabdolali, I can potentially review later this afternoon at the earliest, though may need to be tomorrow morning.  In the meantime is there a test data file I can use to verify?

**Comment by aliabdolali** [comment]
Thanks Matt, it works for me.
the new feature can be tested by executing examples/Example_Directional_Spectral_Density_NDBC_ascii.m
The input is 44100w9999.nc which you can download from this [link](https://dods.ndbc.noaa.gov/thredds/catalog/data/swden/44100/catalog.html?dataset=data/swden/44100/44100w9999.nc). You also need [polarPcolor.m](https://www.mathworks.com/matlabcentral/fileexchange/49040-pcolor-in-polar-coordinates) or turn visualize='false' in line 30 of examples/Example_Directional_Spectral_Density_NDBC_ascii.m, so it does not visualize.

**Comment by MatthewMasarik-NOAA** [comment]
> Thanks Matt, it works for me. the new feature can be tested by executing examples/Example_Directional_Spectral_Density_NDBC_ascii.m The input is 44100w9999.nc which you can download from this [link](https://dods.ndbc.noaa.gov/thredds/catalog/data/swden/44100/catalog.html?dataset=data/swden/44100/44100w9999.nc). You also need [polarPcolor.m](https://www.mathworks.com/matlabcentral/fileexchange/49040-pcolor-in-polar-coordinates) or turn visualize='false' in line 30 of examples/Example_Directional_Spectral_Density_NDBC_ascii.m, so it does not visualize.

Perfect.  Thank you @aliabdolali.

**Review by ricampos — APPROVED** [review]

**Pull request merged**
