### PR TITLE
Fileformat

### PR DESCRIPTION
**Pull request by ricampos**
# Pull Request Summary
small updates to the time arrays and variable names, to avoid problems when using different file formats. 

## Description
WW3-tools can read netcdf and grib2 formats for the field outputs. These file formats and reading/opening processes lead to different time arrays and standards as well as different variable names. It is also the case when converting grib2 to .nc using wgrib2 or CDO, when the time arrays and variable names produced are also different. The new updates have been designed to be able to work with all these different formats without breaking.

### Issue(s) addressed
Updates in 
ww3fields.py
modelSat_collocation.py
modelBuoy_collocation.py
to handle different file formats without problems.

### Commit Message
small updates to the time arrays and variable names, to avoid problems when using different file formats. 
 
### Testing
New codes were tested with:
- grib2 file format from ww3.
- netcdf file format from ww3
- netcdf file format converted from grib2 (ww3) using CDO and wgrib2
The modelBuoy_collocation.py was tested only with netcdf file format from ww3 as it related to point output (no grib2 format available).
ww3fields.py was also tested with structured and unstructured grids, and both array structures works fine.

### CODE REVIEW

**Comment by MatthewMasarik-NOAA** [comment]
@sbanihash will be handling the review of this PR.

**Comment by sbanihash** [comment]
@MatthewMasarik-NOAA  @ricampos I will work on this PR next week. Right now I don't have the right python setup on Hera to do so and fixing that issue would require some time. Based on my other priorities, I will attend to this task later.

**Comment by MatthewMasarik-NOAA** [comment]
Thanks @sbanihash for the timeline.  Please keep us posted as you work through the review.

**Comment by sbanihash** [comment]
Thank you @ricampos for the changes. I will go ahead and test the new code.

**Comment by MatthewMasarik-NOAA** [comment]
Fyi @sbanihash @ricampos I just mentioned this offline to Ricardo, but this branch needs to be synced up because it is one commit behind.  And now it has merge conflicts. Ricardo, please try syncing this branch, it's unlikely it's going to help with the conflict, but lets try.  In event it doesn't let me know and we will set up a Meet to resolve it.

**Pull request closed without merging**
