### PR TITLE
More flexibility in input file formats, new function wproc to handle ensemble members, and further improvements in pvalstats.py (Class and OOP)

### PR DESCRIPTION
**Pull request by ricampos**
# Pull Request Summary
More flexibility in input file formats, new function wproc to handle ensemble members, and further improvements in pvalstats.py (Class and OOP)

## Description
More flexibility in input file formats, grib2 and netcdf, has been added, including different variable names.
A new function wproc was written to help deal with ensemble members after model/sat collocation.
The module pvalstats.py was rebuilt using python Class and OOP.

### Issue(s) addressed
- prepGridMask.py, modelSat_collocation.py, and ww3fields.py had problems with the input file format for the wave fields, as well as the conflict with variable names. It has been fixed to work with netcdf and grib2 formats and different variable names.
- collocated files after running modelSat_collocation.py for multiple members might present small differences in the array size (due to quality control criteria and differences in the wave fields of different members), so they could not be appended to create a unified ensemble array (to calculate the ensemble mean for ex.). Now the new code wproc.py can be used to do that, and works well even for very large arrays.
- pvalstats.py was not using Class and OOP, containing many repeated blocks of code and redundancy. It has been completely renovated to use python Class and OOP.

### Commit Message
More flexibility in input file formats, new function wproc to handle ensemble members, and further improvements in pvalstats.py 

### Testing
I tested it on my local laptop and on Orion, at 
/work2/noaa/marine/ricardo.campos/WW3-tools
using the script checkPR.py
It worked well in both environments.

### CODE REVIEW

**Comment by sbanihash** [comment]
The new code has been tested on Hera (NOAA RDHPCS) to evaluate GEFS EP4 outputs. Scripts tested with both netcdf files and grib2. wproc.py is functioning as expected and pvalstats new structure does not cause any issues. 
Changes are approved. Merging is recommended.

**Review by sbanihash — APPROVED** [review]
The new code has been tested on Hera RDHPC to evaluate GEFS EP4 outputs. Scripts tested with both netcdf files and grib2. wproc.py is functioning as expected and pvalstats new structure does not cause any issues. 
Changes are approved.

**Comment by MatthewMasarik-NOAA** [comment]
Thank you for reviewing and approving this PR, @sbanihash.

**Comment by MatthewMasarik-NOAA** [comment]
@ricampos Thank you for these updates related to input format and ensemble members.

**Pull request merged**
