### PR TITLE
Updated the default color palette to improve readability and visibility.

### PR DESCRIPTION
**Pull request by Ghazal-Mohammadpour**
##  Changes Made:
Replaced the original color palette with a new set of colors.
The new colors have been selected to enhance readability and visibility.
### Reasoning: 
The original color palette lacked readability and visibility in certain contexts. The updated colors provide better contrast and are easier to distinguish.

## Testing
Tested the new color palette in various visualization scenarios to ensure improved readability and visibility.

### CODE REVIEW

**Review by JessicaMeixner-NOAA — CHANGES_REQUESTED** [review]
@Ghazal-Mohammadpour Please isolate the changes here to only be those described in your PR description.

**Comment by JessicaMeixner-NOAA** [comment]
@ricampos - we found that some of the default colors like yellow or gold were hard to see and that the navy and the blue were at times hard to distinguish.   

Here's the current list: 
```
np.array(['navy', 'firebrick', 'darkgreen', 'fuchsia', 'gold', 'blue', 'salmon', 'lime', 'darkviolet', 'yellow',
                'cornflowerblue', 'red', 'green', 'violet', 'orange']))
```

and here's the proposed list: 
```
 np.array(['darkred', 'purple', 'darkgreen', 'darkorange', 'deeppink', 'blue', 'brown', 'salmon', 'lime', 'darkviolet', 'yellow',
                'cornflowerblue', 'red', 'green', 'violet', 'orange']))
```

We do not want to break anything that you are already working on.  It looks to me like we potentially could define custom arrays although are having some issues implementing that.   Thoughts?

**Comment by ricampos** [comment]
Nice. Yes, please feel free to modify the style. My taste for colors is very "peculiar", feel free to change.
I would just suggest paying attention to the order where you include them. Because this color array will be used for several functions which will be picking the colors consecutively according to the number of models etc .. So I kept 'navy' and 'firebrick' as the first 2 ones because they distinguish very well and look very sharp (easy to see). As most of the time there are 2 results to be compared, they are the most used. In your case, you would be using 'darkred' and 'purple' which can be more difficult to distinguish.

**Comment by JessicaMeixner-NOAA** [comment]
Good point @ricampos     so maybe: 

```
 np.array([ 'darkblue', 'darkred', 'darkgreen', 'darkorange', 'purple', 'deeppink', 'brown', 'salmon', 'lime', 'darkviolet', 'yellow',
                'cornflowerblue', 'red', 'green', 'violet', 'orange']))
```
???  I don't know we probably should find a table of these colors so we know what we're picking and if they look okay (I tried, but I think I was looking at the wrong table).  I also know everyone will probably have slightly different preferences, so one quick question.  It's my understanding that if we define another array and pass it as color, we should be able to over-write these default colors, is that true?   If so, maybe we should add some instructions on how someone can do that?

**Comment by ricampos** [comment]
I like these colors. I agree with the update.
Yes, you're correct. If you prefer a different color set, you can create and pass it to the function. Easy to customize.

**Review by JessicaMeixner-NOAA — COMMENTED** [review]
Thanks for making the changes.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Approve if @sbanihash and @ricampos also agree with the updates.

**Comment by Ghazal-Mohammadpour** [comment]
@ricampos @JessicaMeixner-NOAA @sbanihash The colors are updated.

**Review by sbanihash — APPROVED** [review]
Changes look good. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
@ricampos just want to confirm with you before merge that this looks okay to you after the updates.

**Comment by ricampos** [comment]
thanks, @JessicaMeixner-NOAA 
Yes, it looks okay.

**Pull request merged**
