### PR TITLE
add example for jonswap and ndbc spectrum

### PR DESCRIPTION
**Pull request by aliabdolali**
# Pull Request Summary
This PR do:
1) fixes bugs in tools/write_directional_spectra_nc.m
2) add an example to generate a jonswap directional spectral density file to the example folder
3) add an example to convert ndbc directional spectral density file to WW3 format
4) add stdmet and swden read functions

* Mention any labels that should be added:  _bug_, _enhancement_

### Commit Message
bug fix in write_directional_spectra_nc.m and add example for jonswap spectrum

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
 
### Testing

* How were these changes tested?
One can execute example/Example_Directional_Spectral_Density_Jonswap.m and it generates a netcdf file
NDBC conversion

bnd_ndbc_ww3 nc

Jonswap BC

boundary nc

### CODE REVIEW

**Comment by ricampos** [comment]
The updates and new versions look good. I would only suggest (not critical) to be able to control the x-axis limits of the power spectrum, to zoom-in more on where the energy is located. Same for the polar plot of the dir spec.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
Thank you @aliabdolali for the update to these matlab scripts for working with directional spectral density.

@ricampos, thank you for your review/approval.  I approve these additions.

**Comment by ricampos** [comment]
Hi Ali and Matt
Quick question: for the review I didn't see a "approve" button, only
comment and close. Where do you click when you review and approve a PR?
Thanks
Ricardo.

**Comment by MatthewMasarik-NOAA** [comment]
Hi Ricardo, I think this might be best to work through an example, to make sure what your seeing in your github account, because it could be a setting thing. Possibly early next week we could make a mock PR and go through the steps?  We can coordinate offline if that sounds good.

**Pull request merged**
