### PR TITLE
Oparchive

### PR DESCRIPTION
**Pull request by ricampos**
# Pull Request Summary
New simplified codes to download NOAA GEFS operational forecasts.

## Description
There are 3 new scripts to download GEFS and GFS forecasts, that replaced the previous structure.
get_gefsWaves.sh will download GEFS wave forecast, for the specific variables of interest.
get_gefsAtmos.sh will download GEFS atmospheric forecast, for the specific variables of interest.
get_gfsWaves.sh will download GFS wave forecast, for the specific variables of interest.
they utilize two pearl codes, get_grib.pl and get_inv.pl, to be able to fetch only the specific variables of interest.

### Issue(s) addressed
It has reduced the number of dependencies and complexity involved in the previous version.
The 2 dependencies are now: wgrib2 and nco, only. The codes are shorter and easier to understand and customize.

### Commit Message
New simplified codes to download NOAA GEFS operational forecasts.

### Testing
The 3 new shell scripts were successfully tested on Orion and using my local laptop (ubuntu).

### CODE REVIEW

**Comment by aliabdolali** [comment]
@ricampos this PR has ~2000 new files, I assume you pushed the libraries by mistake. Otherwise, these are not a part of WW3-tools, right?

**Comment by MatthewMasarik-NOAA** [comment]
@ricampos , I also just noticed what @aliabdolali posted.

**Comment by ricampos** [comment]
@aliabdolali  yes, the first PR included the grib2 folder by mistake. Which I removed in the last PR. Can we move on with the last one ?

**Comment by MatthewMasarik-NOAA** [comment]
> @aliabdolali yes, the first PR included the grib2 folder by mistake. Which I removed in the last PR. Can we move on with the last one ?

@ricampos I can see the first commit adds the libraries, and the second commit has just the three files.  It looks like though the library files are still there.  They may need to be specifically removed from the repo (using `git rm`) to make `git` aware you want them removed from the repo.  You can try that in your repo, then push it again to this branch.  Another option is you could close this PR, then re-submit with just the files you want.

**Comment by ricampos** [comment]
Thanks @MatthewMasarik-NOAA , I didn't know I had to git rm.
I will close this PR and open another one.

**Pull request closed without merging**
