### PR TITLE
WW3 points output:  summary statistics and validation metrics function defs for buoy data

### PR DESCRIPTION
**Pull request by MatthewMasarik-NOAA**
# Pull Request Summary
Adds function definition files that calculate summary statistics and validation metrics from WW3 point output and NDBC buoy data.

## Description
* Two scripts with one function definition each have been added.  Each takes a buoy collocation (netCDF) file as input and can additionally take as optional arguments a WW3 variable name (`'hs'`, `'wnd'`) as well as min/max range for the variable.  If only the collocation file is passed to the function, the WW3 variable defaults to `'hs'` and `min=-inf`, `max=inf`.
* _Note:  Currently just the WW3 variable `'hs'` is supported.  Support for `'wnd'` is in progress._ 

Please also include the following information: 
* Mention any labels that should be added:
  * _enhancement_

### Issue(s) addressed
* Please list any issues associated with this PR, including those the PR will fix/close. 
  * N/A

### Commit Message
WW3 points output:  summary statistics and validation metrics function defs for buoy data

### Check list  
- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
 
### Testing
* These are the first version of these files.  Testing was done by using a driver script to confirm all input argument options behaved as intended.

### CODE REVIEW

**Review by aliabdolali — COMMENTED** [review]
@MatthewMasarik-NOAA are these files going to be in the top directory? or validation?
If it is general for any application (which seems the case), it should go under validations, otherwise we need to make a diretory like `examples` and add GFSv17 related scripts there.

**Comment by MatthewMasarik-NOAA** [comment]
@aliabdolali  this is a good question.  I think for the time being putting them in `validation` makes the most sense.  Possibly as the tool kit grows we may want to revisit.  Let me know if you agree and I can update the PR with them in `validation`.

**Comment by aliabdolali** [comment]
> @aliabdolali this is a good question. I think for the time being putting them in `validation` makes the most sense. Possibly as the tool kit grows we may want to revisit. Let me know if you agree and I can update the PR with them in `validation`.

yes, please go ahead and do it.

**Comment by MatthewMasarik-NOAA** [comment]
@aliabdolali done.

**Review by aliabdolali — APPROVED** [review]

**Pull request merged**
