### PR TITLE
Bug fixes, improvements in modelSat_collocation.py, new satellite (CFOSAT), and new example.

### PR DESCRIPTION
**Pull request by ricampos**
# Pull Request Summary
Updates and bug fixes, especially in modelSat_collocation.py. The matlab_tools folder has been relocated, and a small update on README.md was done. A new example plot_gfsww3_forecast.sh has been included. And a new satellite CFOSAT has been added.

### CODE REVIEW

**Comment by aliabdolali** [comment]
@ricampos you also need to modify all of examples/Example...m and correct the path to matlab_tools directory
just do the following:

`addpath ../ww3tools/matlab_tools > addpath ../matlab_tools`

**Comment by ricampos** [comment]
Thank you, @aliabdolali . I have just edited this part in the two Matlab scripts.

**Review by aliabdolali — APPROVED** [review]
Thanks @ricampos 
I just reviewed the code, but have not tested it.

**Review by MatthewMasarik-NOAA — APPROVED** [review]
Thank you, @ricampos, for these bug fixes and capability upgrades!!

**Pull request merged**
