### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by ricampos**
# Pull Request Summary
New documentation and a small update in the validation.

### CODE REVIEW

**Review by aliabdolali — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
@ricampos we should be very careful about putting binary files in github repositories.  So the *.pdf you might want to make sure you really want it in this repo.

**Comment by JessicaMeixner-NOAA** [comment]
Looking forward to reading and using the updated documents though!

**Comment by ricampos** [comment]
Hi @JessicaMeixner-NOAA , I didn't know about the pdf. This is a conference poster, which won't be modified/updated. The pdf file is not crucial here but the two png figures (also static) are very important. What would you suggest? Keep only the two .png figures in docs?
Thank you

**Comment by JessicaMeixner-NOAA** [comment]
That would be my recommendation @ricampos but it's already in the repository, so at this point it's just there.  Moving forward I would not add any additional pdf's to the repo.

**Comment by ricampos** [comment]
Yes, I understand. Thank you.

**Pull request merged**
